# Generated by Django 4.2.4 on 2023-08-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitantes',
            new_name='Visitante',
        ),
    ]
