# Generated by Django 4.2.4 on 2023-09-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_visitante_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='morador_resposavel',
        ),
        migrations.AddField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.CharField(blank=True, max_length=194, verbose_name='Morador responsável por autorizar a entrada do visitante'),
        ),
    ]
